spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver

# swagger-ui custom path
springdoc.swagger-ui:
  path: "swagger-ui.html"
  disable-swagger-default-url: true
