spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: schema.sql
      mode: always

# swagger-ui custom path
springdoc.swagger-ui:
  path: "swagger-ui.html"
  disable-swagger-default-url: true
