version: '3.8'
services:
  mysql:
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mysqldb
    ports:
      - "3306:3306"