spring:
  r2dbc:
    url: r2dbc:mysql://localhost/mysqldb
    username: mysql
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: schema.sql
      mode: always